[package]
name = "streamswap-interface"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema    = { workspace = true }
cw-vesting         = { workspace = true }
cw-orch            = { workspace = true }
streamswap-types   = { workspace = true }
streamswap-factory = { workspace = true }

[lints]
workspace = true
