[workspace]
members = [
    "contracts/*", "testing"
]
resolver = "2"

[workspace.package]
version    = "0.1.0"
edition    = "2021"
homepage   = ""
repository = ""
license    = "Apache-2.0"
authors = ["Orkun Külçe <orkunkl@users.noreply.github.com>", "Adnan Deniz Çorlu<adenizcorlu@gmail.com"]

[workspace.lints.clippy]
too_many_arguments = "allow"

[workspace.dependencies]
cosmwasm-std = { version = "1.5.5",  features = ["iterator", "staking", "stargate", "cosmwasm_1_2"] }
cosmwasm-schema = "1.2.0"
cw-controllers = " 1.0.1"
cw-storage-plus = "1.0.1"
cw-multi-test= { version = "0.20.1", features = ["cosmwasm_1_2"]}
cw-denom = "2.3.0"
cw-utils = "1.0.1"
cw2 = "1.0.1 "
cw-vesting = { version = "2.3.0", features = ["library"] }
schemars = "0.8.11"
serde = { version = "1.0.152", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.38" }
semver = "1.0.16"
osmosis-std = "0.24.0"
streamswap-stream = { path = "contracts/streamswap-stream" }
streamswap-factory = { path = "contracts/streamswap-factory" }
prost = {version = "0.12.3", default-features = false, features = ["prost-derive"]}

[workspace.metadata.scripts]
optimize = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/workspace-optimizer:0.12.8
"""